
name: Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        application: e-paperback
        environment: E-paperback-env
        version_label: 2f51ab1eefda626d8e9231c7b63a66a9834b6079
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        wait_for_deploy: true
        recovery_wait_time: 30
        use_existing_version_if_available: true

